import { Inter } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "./utils/themeProvider";
import Header from "./ui/header/header";

const inter = Inter({ subsets: ["latin"] });
// const InterVariable = localFont({ src: "./fonts/InterVariable.ttf" });

export const metadata = {
  title: "Salah Mohsen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={
          (inter.className,
          "bg-light dark:bg-night text-night dark:text-light text-pretty antialiased font-medium transition-colors duration-500 ease-in-out ")
        }
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
